---
title: "Resume"
output: html_document
hidedate: true
hiderelated: true
hidediscus: true
---
#Lingke Jiang
# 708-860-6589
#jlk.lincole@utexas.edu

EDUCATION
	Aug.2018-Present       University of Texas, Austin
Cumulative GPA: 3.9057
	Aug.2016-Jun.2018      International Department, Affiliated HS of SCNU (HFI)
                        TOEFL: 110, SAT: 1490
	Sep.2015-Jul.2016       International Department, Guangdong Experimental High School
	Feb.2013-Jul.2015       Guangzhou No.86 Junior Middle School
RESEARCH EXPERIENCES
	Directed Reading Program (Advisor: Gallian Grindstaff)     5 hrs/wk  Fall 2019 & Spring 2020
Presentation: Tuning Curves in Computational Neuroscience (Fall 2019)
Write-up: Finite Spaces Tweaks and Twerks (Spring 2020)
	Freshman Research Initiative (Stream of Magnetic Matter)   6 hrs/wk         Spring 2019
Participated as a fellow researcher to study the design and development of materials for use in data storage, optics, sensors, and optical and infrared astronomy.
	Research at Pioneer Academics                         20 hrs/wk-8wks/yr  10th grade
Proposed an anti-HIV vaccine made of glycopeptide conjugate under the guidance of Professor Nicole Snyder from Davidson College.
EXTRACURRICULAR ACTIVITIES
	Gamma Iota Sigma                                  5hrs/wk-40 wks/yr Spring 2019-now
Worked as an active to have arranged weekly events and hangouts
	Toastmasters Club                                   3hrs/wk-20wks/yr  10th grade-now
Attended weekly conferences to have practiced public speaking; recruited new members to the club.
	Tennis Training                                     3hrs/wk-40wks/yr   11th grade-now
	Debate Club                                        2 hrs/wk-33wks/yr   10-12th grade
Organized on-campus debate competitions, recruited five members to the club in HFI, represented the club at Experimental High to have attended regional debate tournaments
COMMUNITY SERVICE
	COVID Testing Site                                 60hrs/wk    Winter 2020
Volunteered to do data entry and patient registration for Eimg Testing in Brooklyn NYC
	Volunteer Work at Central Texas Food Bank              4hrs/wk    mid-March 2020-now
Volunteered to help sort donated foods in assembly line; food delivery to communities of need.
	Rotational Duties and Research Assistant at The Second Affiliated Hospital of Guangzhou Medical University                                         8hrs/day-8wks/yr   Summer 2019
Volunteered as an assistant in rotational duties and as a research assistant at the neurology department of the hospital; inquired patient history and kept patient records under supervision of on-call doctors for rotational duties; served as a research assistant in neurobiology lab
	Volunteer Work at Guangzhou Welfare Center for Children   5hrs/wk-40wks/yr  10, 11, 12
Substituted as the instructor to teach and take care of an entire class of children (mostly from 3 to 5 years old). Organized monthly cleaning events; Administered celebration events for special occasions like the New Year, Spring Festival, and Mid-Autumn Festival.
WORK EXPERIENCES
	Sanger Learning Center                                 5hrs/wk-10wks/yr  Junior--now
Working as tutor for appointment tutoring on maths and physics.
HONORS & AWARDS
	College Scholars Honoree of College of Natural Sciences of UT Austin in Spring 2020
	2nd Prize in 2017 Instrumental Music Competition of Affiliated High School of SCNU for Piano Performance
	3rd Prize in 2017 CCTV Star of Outlook English Talent Competition National Final
	Top Ten Speaker at NHSDLC (National High School Debate League of China) of Guangzhou Regional Debate Tournament in Fall 2016
SKILLS
	Language
	Fluent in Mandarin, Cantonese, and English
	Programming
	Fluent in Python, Java.

<center>
<iframe src="/resume.pdf" width="100%" height="800" border="0"></iframe>
</center>
